[build-system]
requires = ['setuptools>=45', 'wheel']
build-backend = 'setuptools.build_meta'

[project]
dynamic = ["dependencies"]
version = "0.0.1"
name = 'cai4py'                       # short for "counting automaton implementation for python"
requires-python = '>=3.13'

[tool.setuptools.packages.find]
where = ["src"] # The location of the package(s) to install

[tool.setuptools-scm]
write_to = "src/cai4py/_version.py"
version_scheme = "semantic"

[tool]
black.line-length = 80
isort.profile = "google"
