from setuptools import setup, find_packages

setup(
    name="cai4py",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "contourpy",
        "cycler",
        "fonttools",
        "importlib_resources",
        "kiwisolver",
        "matplotlib",
        "numpy",
        "packaging",
        "pillow",
        "pyparsing",
        "python-dateutil",
        "six",
        "tikzplotlib",
        "timeout-decorator",
        "webcolors",
        "xeger",
        "zipp",
        "pylint",
        "black",
        "coverage",
        "tqdm",
        "memory_profiler",
        "pandas",
        "ipykernel",
        "seaborn",
    ],
    python_requires=">=3.14",
)
